const state={headers:[],rows:[],users:[],source:'',sheetId:'',tabName:'WISHLIST'};
const els={sheetId:gid('sheetId'),tabName:gid('tabName'),loadSheetBtn:gid('loadSheetBtn'),csvPaste:gid('csvPaste'),parseCsvBtn:gid('parseCsvBtn'),csvFile:gid('csvFile'),searchInput:gid('searchInput'),userSelect:gid('userSelect'),statusFilter:gid('statusFilter'),clearFiltersBtn:gid('clearFiltersBtn'),profileTitle:gid('profileTitle'),profileCount:gid('profileCount'),profileList:gid('profileList'),compareA:gid('compareA'),compareB:gid('compareB'),compareResults:gid('compareResults'),newUserName:gid('newUserName'),addUserBtn:gid('addUserBtn'),newPokemonName:gid('newPokemonName'),newPokemonForm:gid('newPokemonForm'),addPokemonBtn:gid('addPokemonBtn'),exportCsvBtn:gid('exportCsvBtn'),exportJsonBtn:gid('exportJsonBtn'),resetLocalBtn:gid('resetLocalBtn'),toast:gid('toast')};
function gid(id){return document.getElementById(id)}
function toast(msg){els.toast.textContent=msg;els.toast.classList.add('show');setTimeout(()=>els.toast.classList.remove('show'),2200)}
function save(){localStorage.setItem('tradeListApp',JSON.stringify(state))}
function loadLocal(){try{const s=JSON.parse(localStorage.getItem('tradeListApp')||'null');if(s&&s.rows){Object.assign(state,s)}}catch(e){}}
function csvUrl(id,tab){return 'https://docs.google.com/spreadsheets/d/'+encodeURIComponent(id)+'/gviz/tq?tqx=out:csv&sheet='+encodeURIComponent(tab||'WISHLIST')}
async function loadSheet(){const id=els.sheetId.value.trim();const tab=els.tabName.value.trim()||'WISHLIST';if(!id)return toast('Paste a Sheet ID first');const res=await fetch(csvUrl(id,tab));if(!res.ok)throw new Error('Could not load sheet. Make sure it is public or shared for viewing.');const text=await res.text();loadCsv(text,'sheet:'+tab);state.sheetId=id;state.tabName=tab;save();toast('Loaded '+tab)}
function parseCsv(text){const rows=[];let row=[],cur='',q=false;for(let i=0;i<text.length;i++){const c=text[i],n=text[i+1];if(c==='"'&&q&&n==='"'){cur+='"';i++}else if(c==='"'){q=!q}else if(c===','&&!q){row.push(cur);cur=''}else if((c==='\n'||c==='\r')&&!q){if(c==='\r'&&n==='\n')i++;row.push(cur);if(row.some(x=>String(x).trim()!==''))rows.push(row);row=[];cur=''}else cur+=c}row.push(cur);if(row.some(x=>String(x).trim()!==''))rows.push(row);return rows}
function toCsv(matrix){return matrix.map(r=>r.map(v=>{v=String(v??'');return /[",\n]/.test(v)?'"'+v.replaceAll('"','""')+'"':v}).join(',')).join('\n')}
function loadCsv(text,source){const m=parseCsv(text);if(!m.length)return toast('No rows found');state.headers=m[0].map(x=>x.trim());state.rows=m.slice(1).map(r=>state.headers.map((_,i)=>r[i]||''));state.source=source||'csv';inferUsers();save();render();}
function inferUsers(){const headers=state.headers;let start=1;const first=headers.map(h=>h.toLowerCase());const idx=first.findIndex(h=>['pokemon','pokémon','name','mon'].includes(h));if(idx>=0)start=idx+1;state.users=headers.slice(start).filter(Boolean)}
function pokemonFrom(row){const headers=state.headers.map(h=>h.toLowerCase());let nameIndex=headers.findIndex(h=>['pokemon','pokémon','name','mon'].includes(h));if(nameIndex<0)nameIndex=0;const raw=row[nameIndex]||'';const parsed=parsePokemonName(raw);return {...parsed,rawName:raw,row}}
function parsePokemonName(raw){let s=String(raw||'').trim();let form='';const rules=[[/^a[- ]/i,'Alolan'],[/^g[- ]/i,'Galarian'],[/^h[- ]/i,'Hisuian'],[/^p[- ]/i,'Paldean'],[/origin/i,'Origin']];for(const [re,label] of rules){if(re.test(s)){form=label;s=s.replace(re,'').trim();break}}return {name:s||'(unnamed)',form}}
function parseCell(raw){const v=String(raw||'').trim();const upper=v.toUpperCase();const statuses=[];['H','M','L'].forEach(x=>{if(new RegExp('(^|[^A-Z])'+x+'([^A-Z]|$)').test(upper))statuses.push(x)});const lower=v.toLowerCase();const gender=lower.includes('(f)')?'female':lower.includes('(m)')?'male':'';const sizes=['xxs','xs','xxl','xl'].filter(x=>lower.includes(x));return {raw:v,statuses,gender,sizes,notes:v}}
function entriesForUser(user){const idx=state.headers.indexOf(user);if(idx<0)return[];return state.rows.map((r,i)=>({i,...pokemonFrom(r),cell:parseCell(r[idx]),user})).filter(e=>e.cell.raw)}
function currentEntries(){const user=els.userSelect.value;let list=entriesForUser(user);const q=els.searchInput.value.trim().toLowerCase();const st=els.statusFilter.value;if(q)list=list.filter(e=>(e.name+' '+e.form+' '+e.cell.raw).toLowerCase().includes(q));if(st)list=list.filter(e=>e.cell.statuses.includes(st));return list}
function render(){renderUsers();renderProfile();renderCompare();}
function renderUsers(){[els.userSelect,els.compareA,els.compareB].forEach(sel=>{const old=sel.value;sel.innerHTML=state.users.map(u=>'<option>'+escapeHtml(u)+'</option>').join('');if(state.users.includes(old))sel.value=old});if(!els.compareB.value&&state.users[1])els.compareB.value=state.users[1]}
function renderProfile(){const user=els.userSelect.value||state.users[0]||'';els.profileTitle.textContent=user?user+' profile':'Profile';const list=currentEntries();els.profileCount.textContent=list.length+' shown';els.profileList.innerHTML=list.length?list.map(card).join(''):'<div class="empty">Load a sheet or CSV to see entries.</div>'}
function card(e){const pills=[...e.cell.statuses,e.form,e.cell.gender,...e.cell.sizes].filter(Boolean).map(x=>'<span class="pill">'+escapeHtml(x)+'</span>').join('');return '<div class="card"><h3>'+escapeHtml(e.name)+'</h3><div>'+pills+'</div><div class="raw">'+escapeHtml(e.cell.raw)+'</div></div>'}
function hasWant(e){return e.cell.statuses.includes('H')||e.cell.statuses.includes('M')||/lf|want|need|wish/i.test(e.cell.raw)}
function hasHave(e){return e.cell.statuses.includes('L')||/ft|have|extra|trade/i.test(e.cell.raw)}
function renderCompare(){const a=els.compareA.value,b=els.compareB.value;if(!a||!b||a===b){els.compareResults.innerHTML='<div class="empty">Pick two different users.</div>';return}const ea=entriesForUser(a),eb=entriesForUser(b);const key=e=>e.name.toLowerCase()+'|'+e.form.toLowerCase();const mapA=new Map(ea.map(e=>[key(e),e]));const mapB=new Map(eb.map(e=>[key(e),e]));const aGives=[],bGives=[];mapA.forEach((x,k)=>{const y=mapB.get(k);if(y&&hasHave(x)&&hasWant(y))aGives.push(x);if(y&&hasWant(x)&&hasHave(y))bGives.push(y)});els.compareResults.innerHTML='<div class="grid"><div><h3>'+escapeHtml(a)+' may offer '+escapeHtml(b)+'</h3>'+listCards(aGives)+'</div><div><h3>'+escapeHtml(b)+' may offer '+escapeHtml(a)+'</h3>'+listCards(bGives)+'</div></div>'}
function listCards(list){return list.length?list.map(e=>'<div class="card match"><b>'+escapeHtml(e.name)+'</b> '+(e.form?'<span class="pill">'+escapeHtml(e.form)+'</span>':'')+'<div class="raw">'+escapeHtml(e.cell.raw)+'</div></div>').join(''):'<div class="empty">No obvious matches from shorthand yet.</div>'}
function addUser(){const name=els.newUserName.value.trim();if(!name)return;if(state.headers.includes(name))return toast('User already exists');state.headers.push(name);state.rows=state.rows.map(r=>[...r,'']);inferUsers();save();render();els.newUserName.value='';toast('User added')}
function addPokemon(){const name=els.newPokemonName.value.trim();if(!name)return;const form=els.newPokemonForm.value.trim();const row=state.headers.map((_,i)=>i===0?(form?form+' '+name:name):'');state.rows.push(row);save();render();els.newPokemonName.value='';els.newPokemonForm.value='';toast('Pokemon row added')}
function download(name,text,type){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([text],{type}));a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),500)}
function exportCsv(){download('trade-list-export.csv',toCsv([state.headers,...state.rows]),'text/csv')}
function exportJson(){download('trade-list-export.json',JSON.stringify(state,null,2),'application/json')}
function escapeHtml(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
els.loadSheetBtn.onclick=()=>loadSheet().catch(e=>toast(e.message));els.parseCsvBtn.onclick=()=>loadCsv(els.csvPaste.value,'paste');els.csvFile.onchange=e=>{const f=e.target.files[0];if(!f)return;f.text().then(t=>loadCsv(t,f.name))};els.searchInput.oninput=renderProfile;els.userSelect.onchange=renderProfile;els.statusFilter.onchange=renderProfile;els.clearFiltersBtn.onclick=()=>{els.searchInput.value='';els.statusFilter.value='';renderProfile()};els.compareA.onchange=renderCompare;els.compareB.onchange=renderCompare;els.addUserBtn.onclick=addUser;els.addPokemonBtn.onclick=addPokemon;els.exportCsvBtn.onclick=exportCsv;els.exportJsonBtn.onclick=exportJson;els.resetLocalBtn.onclick=()=>{localStorage.removeItem('tradeListApp');location.reload()};loadLocal();if(state.sheetId)els.sheetId.value=state.sheetId;if(state.tabName)els.tabName.value=state.tabName;render();